version: "3.8"

services:
  recieipt-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receipt-processor
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run start
